name: Run Pytest on PRs

on:
  pull_request:
    branches:
      - master
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: "3.12"
    
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          version: 0.6.5

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version" 
        
      - name: Install the project
        run: uv sync --all-extras --dev
        
      - name: Run tests
        run: uv run pytest tests
