name: Rust Tests

on:
  pull_request:
    branches:
      - master
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/src/rtmdet-object-detection/Cargo.lock') }}
      
      - name: Run cargo test
        run: make test-rust